### PR TITLE
Allow dynamic context callbacks for link and form tracking

### PR DESCRIPTION
**Pull request by jethron**
See #519 

Allows for more flexible contexts to be dynamically added to the events for link clicks, form changes, and form submissions. This works similarly to the context callbacks in pageviews/pagepings, just extended to these other types. Unlike in pageviews/pagepings, the Arrays of static and dynamic contexts are not kept separate, in order to maintain the public function interfaces' backward+forward compatibility. 

It lets you do things like the below, without having to update the core link click schema with your additional data:
```javascript
function dataAttributesContext(el) {
    if (el.getAttribute('data-product-id') && el.getAttribute('data-product-category')) return {
        'schema': 'iglu:com.example.snowplow/web_page/link_product_data/1-0-0',
        'data': {
            'productId': el.getAttribute('data-product-id'),
            'productCategory': el.getAttribute('data-product-category')
        }
    }
}

function cssPathContext(el){
    var path = [];

    while (el !== null && !el.isSameNode(document.body)) {
        var level = el.nodeName.toLowerCase();
        if (el.id) level += '#' + el.id;
        if (el.className) level += '.' + el.getAttribute('class').split(/\s+/g).join('.');

        if (!el.id && el.parentNode.childElementCount > 1) {
            level += ':nth-child(' + (Array.prototype.indexOf.call(el.parentNode.children, el) + 1) + ')';
        }

        el = el.parentNode;
        path.push(level);
    }

    return {'schema': 'iglu:com.finder.snowplow/web_page/element_position/1-0-0',
    'data': {cssPath: path.reverse().join('>')}};
}

snowplow('enableLinkClickTracking', null, true, true, [dataAttributesContext, cssPathContext]);
```

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by jethron** [comment]
I'm staff at Snowflake Analytics who have already signed the CLA.

**Comment by alexanderdean** [comment]
Hey @jethron - we have to have all contributors from a given co named on a CLA submission. If you speak to @miike he can get this arranged...

**Comment by miike** [comment]
@alexanderdean I can find the Google Sheets form but nowhere to edit it - is there somewhere I can edit the corporations Github usernames directly or should I just get @jethron to fill in the corporate contributor form?

**Comment by alexanderdean** [comment]
Hi @miike - it's fine just to do another entry with @jethron (and any other contributors') details...

**Comment by miike** [comment]
Done!

**Comment by jethron** [comment]
Thanks both!

**Comment by snowplowcla** [comment]
Confirmed! @jethron has signed the Software Grant and Corporate Contributor License Agreement. Thanks so much.

**Comment by alexanderdean** [comment]
@chuwy we are pending a review from you.

**Comment by alexanderdean** [comment]
> Though I would change object.warn('Exception thrown in dynamic context generator: ' + e); to our own error-tracking

Agree

**Comment by alexanderdean** [comment]
@mhadam why is this one still open against the release?

**Comment by mhadam** [comment]
This one slipped past me somehow - putting together the release, I must have been looking at open 2.9.0 issues and didn't check the PRs (or milestone). I can put this into the 2.10.0 branch now (seems to fulfill #519, so I'll reference it against that).

The only thing I wonder is: should this be modified to pass the old values of `innerElements` to the context generator callback (assuming they pass in a form value transform function)? Otherwise we have the option of passing the new and old `innerElements` or the old `innerElements` and the transform function to be used as needed.

**Comment by alexanderdean** [comment]
No worries @mhadam, pushing back to 2.10.0.

> The only thing I wonder is: should this be modified to pass the old values of innerElements to the context generator callback (assuming they pass in a form value transform function)? Otherwise we have the option of passing the new and old innerElements or the old innerElements and the transform function to be used as needed.

Not sure. @BenFradet @chuwy ?

**Comment by BenFradet** [comment]
>The only thing I wonder is: should this be modified to pass the old values of innerElements to the context generator callback (assuming they pass in a form value transform function)? Otherwise we have the option of passing the new and old innerElements or the old innerElements and the transform function to be used as needed.

I think we're better off keeping the "old" `innerElements` as, in my mind, the context generator shouldn't be modifying them

**Comment by mhadam** [comment]
The context generator wouldn't be modifying them, I was thinking that maybe someone would want to generate a context based on the transformed values of innerElements.

**Pull request closed without merging**
