### PR TITLE
#627 ensure logical cookie name is translated when retrieving cookies

### PR DESCRIPTION
**Pull request by acgray**
#627

### CODE REVIEW

**Comment by snowplowcla** [comment]
@acgray has signed the Individual Contributor License Agreement. Thanks so much

**Comment by alexanderdean** [comment]
Hey @acgray - can you provide some background on this one?

**Comment by alexanderdean** [comment]
Ignore me @acgray, I should have read the associated ticket.

**Comment by alexanderdean** [comment]
This was fixed in 2.9.0, closing PR.

**Pull request closed without merging**
