### PR TITLE
Updating page ping functionality

### PR DESCRIPTION
**Pull request by abiswas-tgam**
Updating page ping functionality to fire at minimum visit length when less than heart beat delay.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by abiswas-tgam** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @abiswas-tgam has signed the Contributor License Agreement. Thanks so much.

**Comment by paulboocock** [comment]
Thank you for the PR. This looks like a nice update to the logic. We'll look to get this merged into 2.15.0.

**Comment by abiswas-tgam** [comment]
Anything we can do, to make the community better 🙌.

**Comment by abiswas-tgam** [comment]
Currently, the unit is failing in exact two places and I believe they are failing for exact same reason. The page ping initiated in first page view don't reset in following page views in case of SPA pages. As a result, we are getting more page pings for SPA pages. I need to do more investigation to understand how those page pings initially setup get reset in following page views.

**Comment by paulboocock** [comment]
This looks to be 90% of the way there. However, in it's current state this breaks IE9 support.
Due to:
https://caniuse.com/#feat=mdn-api_windoworworkerglobalscope_setinterval_supports_parameters_for_callback

I think this can be adjusted and included in 2.15.0 though (which is pretty close to release now!). We will cherry-pick this PR into 2.15.0 and adjust it for IE9 support and fix the unit tests. Thanks for the contribution!

**Pull request closed without merging**
