### PR TITLE
Dynamic context callbacks sometimes return null (close #743)

### LINKED ISSUE #743: Fix dynamic context callbacks sometimes returning null
I have noticed that in some cases result of user supplied function for custom context or custom context itself can be set to `null` instead of proper object. Since presence of one custom custom context not generally critical to event data - the data should not go into bad stream because logic sees `null` instead of context. 

The solution is to sanitize user supplied contexts for "falsy" values. 

In order to do that the following adjustments would be needed in `helpers.js` under `src/js/lib` sub-folder add following:
   - `filter = require("lodash/filter"),` line right after `map = require("lodash/map"),` line
   - Update `object.resolveDynamicContexts` function's return statement and wrap returning `map` function in `filter()` i.e to this:
```
return filter(map(dynamicOrStaticContexts, function(context) {
			if (typeof context === 'function') {
				try {
					return context.apply(null, params);
				} catch (e) {
					//TODO: provide warning
				}
			} else {
				return context;
			}
		}));
```

### PR DESCRIPTION
**Pull request by max-tgam**
This address problem and implements solution described in https://github.com/snowplow/snowplow-javascript-tracker/issues/743

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by max-tgam** [comment]
I signed CLA.

**Comment by snowplowcla** [comment]
Confirmed! @max-tgam has signed the Contributor License Agreement. Thanks so much.

**Comment by max-tgam** [comment]
@colmsnowplow This is the adjustments for https://github.com/snowplow/snowplow-javascript-tracker/issues/743.
I tried to disable prettification on safe but it didn't quite work that is why this PR shows so many changed lines.

**Comment by colmsnowplow** [comment]
Hey @max-tgam, we're making good progress on the improvements to our testing framework, after which we can put this into a release along with another couple of bugfixes.

Could you rename your commit to the following please?:

`Dynamic context callbacks sometimes return null (close #743)`

Thanks for your patience on this.

**Comment by max-tgam** [comment]
@colmsnowplow done.

**Comment by colmsnowplow** [comment]
Smashing, thanks @max-tgam.

**Comment by jamessnowplow** [comment]
Hi @max-tgam.

Just a couple more bits before we can merge this one. 

We are in the process of sorting out some prettier rules for the whole codebase. In the mean time could you remove all the whitespace changes please? It makes it easier to focus on the good work in the commit.

Could you also revert your change around line 34?. The extra semi colon looks pointless but it guards against bundling issues and the prettier comment will cause us problems when we introduce it further down the line.

Thank you again for being patient with us.

**Comment by max-tgam** [comment]
@jamessnowplow I will fix it tomorrow.

**Comment by jamessnowplow** [comment]
Hi @max-tgam,

We'd like to get this one into our next release and we've done a bunch of work around testing in this last couple of weeks. So I've taken the liberty of writing a test for your change and rebased the whole thing on to develop over in this branch:

https://github.com/snowplow/snowplow-javascript-tracker/compare/develop...feature/743-dynamic-null-callbacks

You could either rebase against develop and copy the test over, or we could just go with my branch. I don't want to loose the reference to your contribution though.

**Comment by max-tgam** [comment]
@jamessnowplow I am ok with you deploying your branch. Sorry was sick last week and then had a lot of stuff to deal with at work and had no time to work on this.

**Pull request closed without merging**
