### PR TITLE
Remove browser-plugin-parrable

### LINKED ISSUE #925: Remove Parrable browser plugin
Hi Snowplow, on behalf of Parrable I'd like to request that our browser plugin be removed.

It implements outdated functionality that we introduced 4 years ago (https://github.com/Parrable/snowplow-javascript-tracker/pull/1) and we have not had any installations using the Snowplow Parrable tracker in a long time.

Specifically, the functionality that the Parrable plugin provides is reading an optout cookie which has since been renamed from the value used here.

It appears that you're preparing the v3 release of this repo and now would be a good time to remove the plugin as it's part of the breaking version change.

I can put in the PR to remove our plugin, I just need to know where to look/remove things from. I've gathered this list:

- plugins/browser-plugin-parrable
- rush.json
- common/config/rush.json
- trackers/javascript-tracker/tracker.config.ts
- trackers/javascript-tracker/tracker.lite.config.ts
- trackers/javascript-tracker/configuration.js
- trackers/javascript-tracker/features.ts

I'm not familiar with Rush so if there is an easy command to remove ourselves from its config please let me know.

Finally, the npm (https://www.npmjs.com/package/@snowplow/browser-plugin-parrable) can be marked as depricated.

Feel free to reach out to me at ian@parrable.com with any questions.

### PR DESCRIPTION
**Pull request by icflournoy**
This PR removes the browser-plugin-parrable from this monorepo. After removing the plugin files and editing the rush build config files I ran the `rush update` command which made changes in `common/config/rush/pnpm-lock.yaml`. A local `rush build` passed.

There are build/changelogs in `common/changes/@snowplow/browser-plugin-parrable` - should these be removed as well?

Resolves #925

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by icflournoy** [comment]
I've signed the `Software Grant and Corporate Contributor License Agreement v1.0` CLA.

**Comment by paulboocock** [comment]
Thanks for the PR @icflournoy 

You're right, the change files can also be removed now. 

They are used to generate the CHANGELOG on final release but we won't have this in 3.0.0 now so no need for them.

**Review by paulboocock — APPROVED** [review]

**Comment by paulboocock** [comment]
I've merged this in manually, I ended up with a conflict due to a wider change that mean I touched a file within the Parrable plugin.

Thanks again for the PR! 

Your commit is now here: https://github.com/snowplow/snowplow-javascript-tracker/pull/905/commits/4239ae3d302e7e755c26d4cb3ec2759b24d187c6

I'll close this PR but I'll leave the issue open until v3 is release.

**Comment by icflournoy** [comment]
Thanks, @paulboocock happy to help clear this up.

**Pull request closed without merging**
