### PR TITLE
Update Tracker documentation (close: #605)

### PR DESCRIPTION
**Pull request by chrissherlock**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by chrissherlock** [comment]
I signed the agreement.

**Comment by alexanderdean** [comment]
Hi @chrissherlock - thanks, I took a look but it looks like you entered your GitHub name wrongly. Can you try again?

**Comment by chrissherlock** [comment]
Sorry about that, signed again.

**Comment by snowplowcla** [comment]
@chrissherlock has signed the Individual Contributor License Agreement. Thanks so much

**Comment by alexanderdean** [comment]
@mhadam why is this one still open against the release?

**Comment by mhadam** [comment]
This was pulled into the release with a commit referencing the issue, not the pull request. I think that's why it's not closed out.

**Comment by alexanderdean** [comment]
Cool, thanks closing

**Pull request closed without merging**
