### PR TITLE
Release/3.9.0

### PR DESCRIPTION
**Pull request by igneel64**
Release 3.9.0 containing:
- #1124 
- #1146 
- #1148
- #479 
- #1162 
- #1141 
- #1164 
- #1142 
- #815 
- #1082 
- #1157 

Enhancements:
- Fixes for flaky end-to-end tests
- Add implicit total_quantity calculation on snowplow ecommerce transactions

### CODE REVIEW

**Review by matus-tomlein — COMMENTED** [review]
I just noticed that the `nextBump` property in `version-policies.json` is set to `prerelease`. Make sure to update to `minor` in a prepare for release commit.

**Comment by igneel64** [comment]
@matus-tomlein 
It should probably be `release` to move out of beta, is that right ?

**Comment by matus-tomlein** [comment]
@igneel64 oh right, I think that's true.

**Review by matus-tomlein — APPROVED** [review]
LGTM! 🚀 🚢

**Review by greg-el — APPROVED** [review]
LGTM, builds and runs fine! 🎉

**Pull request merged**
