### PR TITLE
Change all require imports to ES6 imports

### PR DESCRIPTION
**Pull request by warapitiya**
- [x] Move imports to ES6 imports
- [ ] Fix build and test

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by warapitiya** [comment]
I signed it!

**Comment by warapitiya** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @warapitiya  has signed the Individual Contributor License Agreement. Thanks so much

**Comment by paulboocock** [comment]
Hi @warapitiya 
Thank you for your PR. We are currently planning to introduce ES modules as well as modularisation in version 3 of the JS Tracker. With that in mind, this PR is in the right direction doesn't quite fit in with that plan as we envision a grander change that incorporates new build tooling and a wider refactor of the tracker code base. 
However, please don't be discouraged by me closing this PR. We welcome PRs into this repository that fix open issues and we are actively trying to respond and merge changes in quicker than we have in past.

**Pull request closed without merging**
