### PR TITLE
Add method to dissalow brace in url

### PR DESCRIPTION
**Pull request by Nabsterz0r**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by Nabsterz0r** [comment]
I signed it!

**Comment by mhadam** [comment]
Thanks, I'll release this at the end of the day.

**Comment by snowplowcla** [comment]
@Nabsterz0r  has signed the Software Grant and Corporate Contributor License Agreement

**Pull request closed without merging**
