### PR TITLE
Add timestamp to session and different storage compatibility

### PR DESCRIPTION
**Pull request by martynassimkevicius**
* New config `configIsStorageCompatibilityEnabled` for storage type switch compatibility.
* Add TTL to session by https://github.com/snowplow/snowplow-javascript-tracker/issues/718 .
* `StorageStrategy == 'cookieAndLocalStorage'` write to all storage types with config `configIsStorageCompatibilityEnabled`.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by mhadam** [comment]
Hi @martynassimkevicius , would you mind signing the CLA? I'll work to

**Comment by martynassimkevicius** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @martynassimkevicius  has signed the Individual Contributor License Agreement. Thanks so much

**Comment by paulboocock** [comment]
Hi @martynassimkevicius 
Sorry that this never got merged into a release. Unfortunately the tracker has moved on since this PR and we're now in conflict - particularly around TTL support on Local Storage that is now resolved (#718). 
If you still feel we need `configIsStorageCompatibilityEnabled` then I'd encourage you to open an Issue, to better describe why it is required as I'm not sure on the problem it is solving, and perhaps another PR if you wish. We are looking to be more proactive with Issues and PRs, so I hope you aren't too discouraged by me closing this.

**Pull request closed without merging**
