### PR TITLE
504 cookie lifetime

### PR DESCRIPTION
**Pull request by Ouriel**
Pull request for the issue #504 
sorry for the change on other line than 169 and 85.
my emacs reformated the code automaticaly :)

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by Ouriel** [comment]
Done!

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much

**Comment by chuwy** [comment]
Closing in favor of ticket #504. Thanks.

**Pull request closed without merging**
