### PR TITLE
Update tracker core docs to 3.6.0

### PR DESCRIPTION
**Pull request by SamSeabourn**
Noticed that the Readme does not reflect tracker core 3.5.0 so I have updated them accordingly

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by SamSeabourn** [comment]
CLA signed, thanks

**Comment by snowplowcla** [comment]
Confirmed! @SamSeabourn has signed the Contributor License Agreement. Thanks so much.

**Comment by paulboocock** [comment]
Great spot @SamSeabourn!

We'll make sure to merge this in with the next release.

**Review by igneel64 — APPROVED** [review]

**Pull request merged**
