### PR TITLE
Update out_queue.js

### PR DESCRIPTION
**Pull request by IArny**
The problem described in https://github.com/snowplow/snowplow-javascript-tracker/issues/769

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by IArny** [comment]
> Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.
> 
> Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @IArny has signed the Contributor License Agreement. Thanks so much.

**Comment by paulboocock** [comment]
Hi @IArny 
Thank you for your contribution. Apologies that this has taken so long for us to look at.
I can see the issue that this is causing you, we didn't prioritise this for 2.13.0 but we will look at get it into our next release - this might be 2.14.0 or 3.0.0 depending on if we do another Minor release before moving to 3.0.0. We will cherry-pick the commit into our release branch when the time comes.

**Pull request closed without merging**
