### PR TITLE
Make newDocumentTitle variable local

### PR DESCRIPTION
**Pull request by brightwrite-admin**

### CODE REVIEW

**Comment by brightwrite-admin** [comment]
Potentially fixes #558 too.

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by brightwrite-admin** [comment]
Signed.

**Comment by snowplowcla** [comment]
@brightwrite-admin has signed the Individual Contributor License Agreement. Thanks so much

**Comment by alexanderdean** [comment]
This merge has been undone, will all work out fine in the end.

**Pull request merged**
