### PR TITLE
ISSUE-1368 Pass clicked element to dynamic context functions for button click tracking plugin

### PR DESCRIPTION
**Pull request by irenehakes**
Relates to [Issue 1368](https://github.com/snowplow/snowplow-javascript-tracker/issues/1368)

The button click tracking plugin appears to have an undocumented feature for attaching dynamic contexts to each button click, similar to [link click tracking plugin](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/web-tracker/tracking-events/link-click).

The button click tracking plugin's dynamic context function, however, only takes the button click event as an argument. This PR updates this call to also pass in the clicked element.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by irenehakes** [comment]
> Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.
> 
> Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

I signed it

**Comment by snowplowcla** [comment]
Confirmed! @irenehakes has signed the Contributor License Agreement. Thanks so much.

**Review by jethron — COMMENTED** [review]
LGTM!

It's unfortunate we couldn't fit this into v4 as a breaking change, the resulting API inconsistency with the other plugins will be a bit awkward to resolve now.

| Plugin  | Context Arg 1 | Context Arg 2 | Context Arg 3 |
| --- | --- | --- | --- |
| Button  | Event Payload  | - (Element in this PR) | - |
| Link  | Element  | - | - |
| Form (Change/Focus)  | Element  | Element Type | Element Value |
| Form (Submit)  | Element  | `ElementData[]` | - |

It might be worth planning for v5 to unify plugins onto a single object param for dynamic contexts so we can be a bit looser with the interface. For Link and Button at least, getting the actual MouseEvent/PointerEvent for information on the type of click, modifier keys, coordinates, pressure used, etc could be useful in some use cases (as suggested in #1368) so would be nice to add in at some point.

**Review by matus-tomlein — APPROVED** [review]
LGTM, thank you for the contribution @irenehakes!

May I just ask you to add the attached change file to the PR?

Good point, @jethron! Have made an issue for the unification in v5, #1390

[issue-1368_2024-11-22-08-27.json](https://github.com/user-attachments/files/17867265/issue-1368_2024-11-22-08-27.json)

**Pull request merged**
