### PR TITLE
Feature/2.2.1

### PR DESCRIPTION
**Pull request by fblundun**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Looks great! I will get this released this afternoon...

**Comment by fblundun** [comment]
I've just noticed that the PerformanceTiming fix for Safari fails on Firefox - I will try to find something that works for both...

**Comment by alexanderdean** [comment]
Thanks @fblundun - please ping in this thread when fixed...

**Comment by fblundun** [comment]
OK @alexanderdean , it's fixed now!

**Pull request merged**
