### PR TITLE
Add getter for DomainSessionId

### PR DESCRIPTION
**Pull request by falschparker82**
Add getter for DomainSessionId as proposed in Issue #548

### CODE REVIEW

**Comment by chuwy** [comment]
Agree with @BenFradet. Also if #548 going to be implemented I would imagine a method returning object with many properties, rather than multiple methods for each property.

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by zwacky** [comment]
@BenFradet according to these [release notes](https://snowplowanalytics.com/blog/2014/12/15/snowplow-javascript-tracker-2.2.0-released/) the `getDomainUserInfo()` it only prints out the domain user id, not domain session id. There is no other workaround than having a new function to retreive the domainSessionId.

**Comment by BenFradet** [comment]
`getDomainUserid` only gives you back the domain user id.

[`getDomainUserInfo`](https://github.com/snowplow/snowplow-javascript-tracker/blob/3241605666cd29e9538b2bb31789b585c1b2969c/src/js/tracker.js#L1643-L1650) gives you back [the whole content of the domain user id cookie](https://github.com/snowplow/snowplow-javascript-tracker/blob/3241605666cd29e9538b2bb31789b585c1b2969c/src/js/tracker.js#L650-L690) which contains more than just the domain user id and in particular [the session id](https://github.com/snowplow/snowplow-javascript-tracker/blob/3241605666cd29e9538b2bb31789b585c1b2969c/src/js/tracker.js#L684-L687).

**Comment by zwacky** [comment]
Thanks for your reply, I'm still at 2.6.2.
As of now the Domain Session ID is not the same that gets sent out in the pixel in my case ([image](https://i.imgur.com/qo3YN8V.png)).

I will try with the latest snowplow tracker in a bit. But maybe I'm confusing certain fields (?!)

**Comment by BenFradet** [comment]
From the image, it seems that cookies are seen as disabled (we couldn't retrieve the content of the `id` cookie) and so the session id is a regenerated random uuid.

**Comment by alexanderdean** [comment]
What was the conclusion on this one? Merge or close? @BenFradet @chuwy

**Comment by BenFradet** [comment]
I tend to agree with @chuwy that we need to standardize what we're exposing through a single method which will make everything clear, closing.

Nonetheless, thanks a lot for your pull request @falschparker82

**Pull request closed without merging**
