### PR TITLE
Fix custom document title override using setDocumentTitle (close #1317)

### LINKED ISSUE #1317: setDocumentTitle does not override the title for trackPageView event
**Describe the bug**
setDocumentTitle does not override the title for trackPageView event

**To Reproduce**
1. Create tracker
2. Override page title with some custom title`setDocumentTitle("foo bar");`
3. Track page view `trackPageView();`

**Expected behavior**
Page view event should be sent with "foo bar" title, but instead, it's sent with regular document.title.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser Chrome
 - Version 125.0.6422.144 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by marcin-j**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by marcin-j** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @marcin-j has signed the Contributor License Agreement. Thanks so much.

**Review by matus-tomlein — APPROVED** [review]
Thank you for identifying and fixing the bug @marcin-j!

This looks good, but can I please ask you for a small favour – please add the file below at the path `common/changes/@snowplow/browser-tracker-core/marcin-j-master_2024-06-18-05-25.json` and commit in this branch.

[marcin-j-master_2024-06-18-05-25.json](https://github.com/user-attachments/files/15880869/marcin-j-master_2024-06-18-05-25.json)

**Comment by marcin-j** [comment]
HI @matus-tomlein, I've added the file

**Pull request merged**
